### ISSUE TITLE
How to use this package?

### ISSUE THREAD

**Issue by nusendra** [yajra/laravel-datatables-scout#1]
### Summary of problem or feature request
I dont know how to use this package on my Laravel. How to pass parameter to searching, etc. Please make small docs. Thanks sir Arjay :)

### System details
- Operating System : Ubuntu 16.04
- PHP Version : 7.1
- Laravel Version : 5.5
- Laravel-DataTables Version : ^8

**Comment by yajra** [comment]
I wasn't able to get back on this package but as the doc on readme, you can use directly using the ScoutDataTable class. This works almost the same with collection.

> Note: this package is not yet on stable version. Will try complete this when I got the chance.

```php
use Yajra\DataTables\ScoutDataTable;

$model = new App\User;

return (new ScoutDataTable($model))
  ->addColumn(...)
  ...
  ->toJson()
```

This is how I planned it to be added on facade but not yet implemented.

```php
return DataTables::scout($model)
  ->addColumn(...)
  ...
  ->toJson()
```

For search, I only tested this on a basic search. Column search may not work yet if I recall correctly.

**Comment by nusendra** [comment]
ok thanks for the explanation sir arjay
